openapi: 3.0.3
info:
  title:  Comment Photo API
  version: "1"
paths:
  /api/commentPhoto:
    post:
      summary: Add a comment to a photo.
      operationId: commentPhoto
      requestBody:
        required: true
        content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: String
                description: The unique ID of the user adding the comment.
              photoId:
                type: string
                description: The ID of the photo to add the comment to.
              commentText:
                type: string
                description: The text of the comment.
      responses:
        '200':
          description: Comment added successfully.
          content:
            application/json:
              example:
                message: Comment added successfully.
        '400':
          description: Bad request. Invalid input or missing required parameters.
          content:
            application/json:
              example:
                error: Bad request. Invalid input or missing required parameters.
        '404':
          description: User not found.
          content:
            application/json:
              example:
                error: User not found.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error: Internal Server Error.
