openapi: 3.0.3
info:
  title:  Unban User API
  version: "1"
paths:
  /api/unbanUser:
    post:
      summary: Unban un user.
      operationId: unbanUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                followerId:
                  type: string
                  The unique ID of the user who wants to unban another user.
                bannedUserId:
                  type: string
                  description: The unique ID of the user to be unbanned.
      responses:
        '200':
          description: User banned successfully.
          content:
            application/json:
              example:
                message: User banned successfully.
        '400':
          description: Bad request. Invalid input or missing required parameters.
          content:
            application/json:
              example:
                error: Bad request. Invalid input or missing required parameters.
        '404':
          description: User not found.
          content:
            application/json:
              example:
                error: User not found.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error: Internal Server Error.
