openapi: 3.0.3
info:
  title:  Remove Comment Photo
  version: "1"
paths:
  /api/uncommentPhoto:
    post:
      summary: Remove a comment from a photo.
      operationId: uncommentPhoto
      requestBody:
        required: true
        content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: String
                description: The unique ID of the user removing the comment.
              photoId:
                type: string
                description: The ID of the photo to remove the comment to.
              commentId:
                type: string
                description: The id of the comment to be removed.
      responses:
        '200':
          description: Comment removed successfully.
          content:
            application/json:
              example:
                message: Comment removed successfully.
        '400':
          description: Bad request. Invalid input or missing required parameters.
          content:
            application/json:
              example:
                error: Bad request. Invalid input or missing required parameters.
        '404':
          description: User not found.
          content:
            application/json:
              example:
                error: User not found.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error: Internal Server Error.
