openapi: 3.0.3
info:
  title:  Unfollow User API
  version: "1"
paths:
  /api/unfollowUser:
    post:
      summary: Unfollow un user.
      operationId: unfollowUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                followerId:
                  type: string
                  description: The unique ID of the user who wants to unfollow another user.
                followingId:
                  type: string
                  description: The unique ID of the user to be unfollowed.
      responses:
        '200':
          description: User unfollowed successfully.
          content:
            application/json:
              example:
                message: User unfollowed successfully.
        '400':
          description: Bad request. Invalid input or missing required parameters.
          content:
            application/json:
              example:
                error: Bad request. Invalid input or missing required parameters.
        '404':
          description: User not found.
          content:
            application/json:
              example:
                error: User not found.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error: Internal Server Error.
