openapi: 3.0.3
info:
  title:  Remove Like Photo API
  version: "1"
paths:
  /api/unlikePhoto:
    post:
      summary: Remove a like from a Photo.
      operationId: unlikePhoto
      requestBody:
        required: true
        content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: String
                description: The unique ID of the user removing the like from the photo.
              photoId:
                type: string
                description: The ID of the photo to remove the like from.
      responses:
        '200':
          description: Like removed  successfully.
          content:
            application/json:
              example:
                message: Like removed  successfully.
        '400':
          description: Bad request. Invalid input or missing required parameters.
          content:
            application/json:
              example:
                error: Bad request. Invalid input or missing required parameters.
        '404':
          description: User not found.
          content:
            application/json:
              example:
                error: User not found.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error: Internal Server Error.
